

CREATE SEQUENCE SQ_NAC_CD_CACHORRO START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE SQ_NAC_CD_USUARIO START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE;

CREATE TABLE T_NAC_CACHORRO
  (
    cd_cachorro    NUMBER (10) NOT NULL ,
    ds_nome        VARCHAR2 (100) ,
    nr_idade       NUMBER (2) ,
    ds_raca        VARCHAR2 (40) ,
    dt_prev_adocao VARCHAR (20) ,
    ds_status      VARCHAR2 (15) NOT NULL
  ) ;
ALTER TABLE T_NAC_CACHORRO ADD CONSTRAINT PK_T_NAC_CACHORRO PRIMARY KEY ( cd_cachorro ) ;


CREATE TABLE T_NAC_USUARIO
  (
    ds_nome    VARCHAR2 (100) NOT NULL ,
    ds_email   VARCHAR2 (100) NOT NULL ,
    cd_usuario NUMBER (10) NOT NULL,
    ds_senha   VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE T_NAC_USUARIO ADD CONSTRAINT PK_T_NAC_USUARIO PRIMARY KEY (cd_usuario);

CREATE OR REPLACE TRIGGER TGR_SQ_NAC_CD_CACHORRO
BEFORE INSERT ON T_NAC_CACHORRO
FOR EACH ROW
BEGIN
  SELECT SQ_NAC_CD_CACHORRO.NEXTVAL
  INTO   :new.cd_cachorro
  FROM   dual;
END;

CREATE OR REPLACE TRIGGER TGR_SQ_NAC_CD_USUARIO
BEFORE INSERT ON T_NAC_USUARIO
FOR EACH ROW
BEGIN
  SELECT SQ_NAC_CD_USUARIO.NEXTVAL
  INTO   :new.cd_USUARIO
  FROM   dual;
END;


