

CREATE SEQUENCE SQ_NAC_CD_CACHORRO START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE ;

CREATE TABLE T_NAC_CACHORRO
  (
    cd_cachorro    NUMBER (10) NOT NULL ,
    ds_nome        VARCHAR2 (100) ,
    nr_idade       NUMBER (2) ,
    ds_raca        VARCHAR2 (40) ,
    dt_prev_adocao VARCHAR2 (40) ,
    ds_status      VARCHAR2 (15) NOT NULL
  ) ;
ALTER TABLE T_NAC_CACHORRO ADD CONSTRAINT PK_T_NAC_CACHORRO PRIMARY KEY ( cd_cachorro ) ;


CREATE TABLE T_NAC_USUARIO
  (
    ds_nome    VARCHAR2 (100) NOT NULL ,
    ds_email   VARCHAR2 (100) NOT NULL ,
    ds_usuario VARCHAR2 (50) ,
    ds_senha   VARCHAR2 (100) NOT NULL
  ) ;

CREATE OR REPLACE TRIGGER TGR_SQ_NAC_CD_CACHORRO 
BEFORE INSERT ON T_NAC_CACHORRO
FOR EACH ROW
BEGIN
  SELECT SQ_NAC_CD_CACHORRO.NEXTVAL
  INTO   :new.cd_cachorro
  FROM   dual;
END;


